Repository tennitech/juke, pull requests merged in 2024-11, with the labels that each got.

#34 Implemented Profile Picture Fetcher in `NavigationBar.js`
  jukeos/.gitignore
  jukeos/package-lock.json
  jukeos/src/auth-server/server.js
  jukeos/src/auth-server/serverAuth.js
  jukeos/src/components/Home.js
  jukeos/src/components/NavigationBar.js
  jukeos/src/contexts/spotify.js
Labels: front-end, back-end

#44 Implement Handling of Access Token Invalidation + Library Implementation
  jukeos/src/App.js
  jukeos/src/auth-server/server.js
  jukeos/src/auth-server/serverAuth.js
  jukeos/src/auth-server/spotifyRefresh.js
  jukeos/src/components/Home.js
  jukeos/src/components/Library.js
  jukeos/src/components/LibraryTesting.js
  jukeos/src/components/NavigationBar.js
  jukeos/src/components/Profile.js
  jukeos/src/contexts/spotify.js
  package-lock.json
Labels: enhancement, back-end, security

#63 Home.js is almost complete; ready for back-end to integrate Web Playback SDK
  .DS_Store
  jukeos/src/App.css
  jukeos/src/assets/pause-icon.svg
  jukeos/src/assets/play-icon.svg
  jukeos/src/assets/skip-backward-icon.svg
  jukeos/src/assets/skip-forward-icon.svg
  jukeos/src/auth-server/server.js
  jukeos/src/components/AnimatedBlob.js
  jukeos/src/components/Home.js
  jukeos/src/components/Library.js
  jukeos/src/components/NavigationBar.js
Labels: front-end

#64 Implemented preliminary back-end code structure for Home.js and Recently Played/Spotify API integration
  jukeos/src/components/Home.js
Labels: enhancement, front-end, back-end

#42 Documenting the Code for #43
  jukeos/src/components/Library.js
  jukeos/src/components/NavigationBar.js
  jukeos/src/components/Profile.js
Labels: documentation, enhancement, back-end
