Repository tennitech/juke, pull requests merged in 2025-04, with the labels that each got.

#158 Automatically add 2 "random" songs to the queue if the queue is empty
  jukeos/src/components/Player.js
  jukeos/src/contexts/spotify.js
Labels: enhancement, back-end

#159 Feat: Replace static Library footer PNG with dynamic album art gradient
  jukeos/src/components/Library.js
Labels: enhancement, front-end

#164 Fix Fonts and Spacing
  jukeos/src/components/Profile.js
Labels: front-end

#165 Add recently played info to PlayerContext, autoplay when queue is empty, store recentlyPlayed locally
  jukeos/src/components/Home.js
  jukeos/src/components/Player.js
  jukeos/src/contexts/spotify.js
Labels: back-end

#173 Add Shuffle and loop buttons
  jukeos/src/components/Home.js
Labels: front-end

#176 feat: Add oscillating scrollable text for long titles/artists
  jukeos/src/components/Home.js
  jukeos/src/components/ScrollableText.css
  jukeos/src/components/ScrollableText.js
Labels: enhancement, front-end
